[package]
name = "conveyor_line_inc"
version = "0.0.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.5.0"
bytemuck = "1.16.0"
chrono = "0.4.38"
crossterm = "0.27.0"
globset = "0.4.14"
itertools = "0.13.0"
mlua = { version = "0.9.8", features = ["vendored", "luajit", "serialize"] }
once_cell = "1.19.0"
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.10.0"
regex = "1.10.5"
serde = "1.0.203"
serde_json = "1.0.117"
slotmap = "1.0.7"
strum = { version = "0.26.2", features = ["derive"] }
tap = "1.0.1"
tokio-macros = "2.3.0"
tokio = { version = "1.0.0", features = ["full"] }
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
walkdir = "2.5.0"
weighted_rand = "0.4.2"
paste = "1.0.15"
convert_case = "0.6.0"
toml = "0.8.14"
ratatui = { version = "0.26.3", features = ["serde"] }
ratatui-macros = "0.4.0"
ansi-to-tui = "4.0.1"
tui-scrollview = "0.3.6"
tui-menu = "0.2.1"
throbber-widgets-tui = "0.5.0"
serde_derive = "1.0.203"
postcard = { version = "1.0.8", features = ["alloc", "use-std", "postcard-derive"] }
rusqlite = { version = "0.32.1", features = ["bundled", "serde_json"] }
raylib = { version = "5.0.1", features = ["serde", "serde_json", "with_serde"] }
